"""create transactions risk_scores alerts alert_events

Revision ID: 1fe285a86c40
Revises: 9323b707b05f
Create Date: 2025-12-14 20:12:28.394283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe285a86c40'
down_revision: Union[str, Sequence[str], None] = '9323b707b05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('merchant_category', sa.String(length=100), nullable=False),
    sa.Column('arrondissement', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_date_amount', 'transactions', ['occurred_at', 'amount'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_category'), 'transactions', ['merchant_category'], unique=False)
    op.create_index(op.f('ix_transactions_occurred_at'), 'transactions', ['occurred_at'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_created_at'), 'risk_scores', ['created_at'], unique=False)
    op.create_index('ix_risk_scores_date_score', 'risk_scores', ['created_at', 'score'], unique=False)
    op.create_index(op.f('ix_risk_scores_score'), 'risk_scores', ['score'], unique=False)
    op.create_index(op.f('ix_risk_scores_transaction_id'), 'risk_scores', ['transaction_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('score_snapshot', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_date_score', 'alerts', ['created_at', 'score_snapshot'], unique=False)
    op.create_index('ix_alerts_date_status', 'alerts', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_risk_score_id'), 'alerts', ['risk_score_id'], unique=True)
    op.create_index(op.f('ix_alerts_score_snapshot'), 'alerts', ['score_snapshot'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_events_created_at'), 'alert_events', ['created_at'], unique=False)
    op.create_index('ix_alert_events_date', 'alert_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_date', table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_created_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_score_snapshot'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_score_id'), table_name='alerts')
    op.drop_index('ix_alerts_date_status', table_name='alerts')
    op.drop_index('ix_alerts_date_score', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_risk_scores_transaction_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_score'), table_name='risk_scores')
    op.drop_index('ix_risk_scores_date_score', table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_created_at'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_transactions_occurred_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_category'), table_name='transactions')
    op.drop_index('ix_transactions_date_amount', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
